### ISSUE TITLE
TS2339: Property 'Feature' does not exist on type 'typeof Types'.

### ISSUE THREAD

**Issue by markstos** [RideAmigosCorp/mongoose-geojson-schema#60]
After upgrading a TypeScript file to 3.0.0, I'm getting this error. Investigating it.
